// <auto-generated />
namespace Vidly_MVC_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateTableGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTableGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "202303261029226_updateTableGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
